app_parameters: 
  secret_key: "cs316"
  host_url: "http://vcm-12647.vm.duke.edu"
  # host_url: "http://localhost:5000"
  scope: "user-library-read user-follow-read user-top-read user-read-recently-played"
  debug_mode_on: TRUE
  acct_refresh_time: 2
  
